"""Add image_url and image_public_id to MenuItem

Revision ID: 56194203459c
Revises: 
Create Date: 2026-07-29 17:28:20.890807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56194203459c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_public_id', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_public_id')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
